name: PROMUSICMASTERING
favicon: null
layout_spectrum: 0.19220792618580163
typography_spectrum: 0.13954909751191735
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.8977255641948432
  lightness: 0.08262533717788756
  saturation: 0.8026555778924376
  rhythmicContrast: 0.7153299630153924
purpose: []
