title: 'Test Site '
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 1
  brandStrength: 0.4755639
  lightness: 0.4216792
  brandColors:
    - '#0F0F0F'
    - '#3A3A3A'
    - '#A9A9A9'
    - '#717171'
    - '#D8D8D8'
  rhythmicContrast: 1
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: PROMUSICMASTERING
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.8001253
layout_spectrum: 0.6528822
