title: 'Test Site '
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 1
  brandStrength: 0.4743108
  lightness: 0.4216792
  brandColors:
    - '#151515'
    - '#FFFFFF'
    - '#DADADA'
    - '#707070'
    - '#404040'
  rhythmicContrast: 1
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: PROMUSICMASTERING
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.8001253
layout_spectrum: 0.7763158
