title: 'Test Site '
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 1
  brandStrength: 0.4743108
  lightness: 0.4216792
  brandColors:
    - '#000000'
    - '#7c2380'
    - '#c01a79'
    - '#9e207d'
    - '#d71675'
  rhythmicContrast: 1
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: PROMUSICMASTERING
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.8001253
layout_spectrum: 0.2844611
