name: PROMUSICMASTERING
favicon: null
layout_spectrum: 0.49789
typography_spectrum: 0.90776
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#7c2380'
    - '#c01a79'
    - '#9e207d'
    - '#d71675'
  brandStrength: 1
  lightness: 0
  saturation: 1
  rhythmicContrast: 0
purpose: []
