name: PROMUSICMASTERING
favicon: null
layout_spectrum: 1
typography_spectrum: 0.79458
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#7c2380'
    - '#c01a79'
    - '#9e207d'
    - '#d71675'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
